# Generated by Django 5.2.10 on 2026-01-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=20)),
                ('audit_type', models.CharField(choices=[('Accounting', 'Accounting'), ('Auditing', 'Auditing'), ('Bookkeeping', 'Bookkeeping'), ('Tax Consultancy', 'Tax Consultancy'), ('Feasibility Study', 'Feasibility Study')], max_length=50)),
                ('audit_year', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
