# Generated by Django 5.2.10 on 2026-01-22 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Invoice', 'Invoice'), ('Bank Statement', 'Bank Statement'), ('Expense File', 'Expense File'), ('Audit Report', 'Audit Report'), ('Other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='audit_documents/')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client')),
            ],
        ),
    ]
